from django.contrib import admin
from .models import *

admin.site.register(User)
admin.site.register(Site)
admin.site.register(Blocks)
admin.site.register(metersInfo)
admin.site.register(site_data)
admin.site.register(site_manager_info)
admin.site.register(saving)
admin.site.register(Threshold_value)
admin.site.register(is_saving)
admin.site.register(dg_data)
admin.site.register(customer)
admin.site.register(PFThreshold)
admin.site.register(carbonEmission)
admin.site.register(alarms)
admin.site.register(VoltageThreshold)
admin.site.register(pf_threshold)
admin.site.register(dg_info)
admin.site.register(HomeGatewayId)
admin.site.register(AisleGroup)
admin.site.register(lights)
admin.site.register(consumption)
admin.site.register(sensors)
admin.site.register(powersource)

