# Generated by Django 5.2.3 on 2025-06-19 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alarms_carbonemission_customer_dg_data_dg_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisle_blocks',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='metersinfo',
            name='SITE_TYPE',
        ),
        migrations.AddField(
            model_name='threshold_value',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.site'),
        ),
        migrations.AlterField(
            model_name='aislegroup',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.site'),
        ),
    ]
