# Generated by Django 5.2.3 on 2025-06-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_aisle_blocks_site_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aisle_blocks',
            new_name='Blocks',
        ),
        migrations.RenameModel(
            old_name='phaseCurrent',
            new_name='PFThreshold',
        ),
        migrations.RemoveField(
            model_name='lights',
            name='aisle_blocks',
        ),
        migrations.RemoveField(
            model_name='threshold_value',
            name='site',
        ),
    ]
